### ISSUE TITLE
I can't install doto via brew

### ISSUE THREAD

**Issue by Dbz** [tksfz/homebrew-doto#1]
It's really important for me to be able to install doto without doing any work.

```
$ brew install doto
Error: No available formula with the name "doto"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
This similarly named formula was found:
xdotool
To install it, run:
  brew install xdotool
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by tksfz** [comment]
@Dbz can you try `brew install tksfz/doto/doto`? That should be working. I'd love if you tried it and let me know. Thanks for checking it out!

**Comment by Dbz** [comment]
This worked! You should add it to the readme on this repo and the doto repo

**Comment by tksfz** [comment]
Right. Done.

Do you have ideas for features you need in doto?

My next thing I think is actually letting you add more detailed content to
tasks in doto (description fields).

**Comment by Dbz** [comment]
Yes, I'd like to add or edit anything in vim. My own to do list I made is
all vim, and for me to switch to this I need to be able to vim

**Comment by tksfz** [comment]
I'd launch vim only to edit long description fields (like the exceptions you've reported in Github issues).

Before doto I used vim to maintain my todo list. But since doto I haven't missed it. I use `doto add` etc. to edit the todo list.

**Comment by Dbz** [comment]
Sometimes I add lots of notes to do to items, so editing a description with
vim (or creating and editing at the same time) is pretty important for me.

**Comment by tksfz** [comment]
Got it. That makes sense. I'm going to add that next.

**Comment by Dbz** [comment]
Awesome. I'm looking forward to switching my todo list to doto.
